import { useNavigate } from 'react-router-dom';

const s = {
  page: { minHeight: '100vh', background: '#06090f', fontFamily: "'Plus Jakarta Sans', sans-serif", color: '#fff' },
  nav: { padding: '14px 36px', borderBottom: '1px solid rgba(255,255,255,0.05)', display: 'flex', alignItems: 'center', gap: 12 },
  back: { background: 'none', border: 'none', color: 'rgba(255,255,255,0.4)', cursor: 'pointer', fontFamily: 'inherit', fontSize: 13 },
  inner: { maxWidth: 760, margin: '0 auto', padding: '48px 24px 80px' },
  h1: { fontFamily: "'Fraunces', serif", fontSize: 40, fontWeight: 900, marginBottom: 8 },
  updated: { fontSize: 12, color: 'rgba(255,255,255,0.35)', marginBottom: 40 },
  h2: { fontFamily: "'Fraunces', serif", fontSize: 22, fontWeight: 700, color: '#fff', marginTop: 36, marginBottom: 12 },
  p: { fontSize: 14, color: 'rgba(255,255,255,0.7)', lineHeight: 1.75, marginBottom: 14 },
  li: { fontSize: 14, color: 'rgba(255,255,255,0.7)', lineHeight: 1.75, marginBottom: 6, marginLeft: 20 },
};

export default function TermsOfService() {
  const navigate = useNavigate();
  return (
    <div style={s.page}>
      <style>{`@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@400;600;700&family=Fraunces:opsz,wght@9..144,700;9..144,900&display=swap');`}</style>
      <nav style={s.nav}>
        <button style={s.back} onClick={() => navigate(-1)}>← Back</button>
        <span style={{ color: 'rgba(255,255,255,0.2)' }}>·</span>
        <span style={{ fontSize: 14, fontWeight: 700 }}>Terms of Service</span>
      </nav>
      <div style={s.inner}>
        <h1 style={s.h1}>Terms of Service</h1>
        <p style={s.updated}>Last updated: 31 May 2026</p>

        <p style={s.p}>By using WanderZenAI you agree to these terms. Please read them carefully.</p>

        <h2 style={s.h2}>1. Service description</h2>
        <p style={s.p}>WanderZenAI is an AI-powered slow travel itinerary generator. We use artificial intelligence to create personalised travel plans. Itineraries are suggestions only — always verify venue details, opening hours, prices, and availability before your trip.</p>

        <h2 style={s.h2}>2. Account</h2>
        <ul>
          <li style={s.li}>You must be 16 or older to create an account</li>
          <li style={s.li}>You are responsible for maintaining the security of your account</li>
          <li style={s.li}>One account per person — no sharing accounts</li>
          <li style={s.li}>We reserve the right to suspend accounts that violate these terms</li>
        </ul>

        <h2 style={s.h2}>3. Free tier and payments</h2>
        <ul>
          <li style={s.li}>Free accounts include 1 itinerary per calendar month</li>
          <li style={s.li}>Paid plans are processed by Stripe — see our Pricing page for current rates</li>
          <li style={s.li}>Monthly subscriptions renew automatically — cancel any time from Settings</li>
          <li style={s.li}>Refunds are handled case-by-case — contact travel@wanderzenai.com</li>
        </ul>

        <h2 style={s.h2}>4. AI-generated content</h2>
        <p style={s.p}>Itineraries are generated by AI (Anthropic Claude) and may contain inaccuracies. WanderZenAI does not guarantee the accuracy, availability, or suitability of any recommended venues, activities, or travel information. You use all travel suggestions at your own risk.</p>

        <h2 style={s.h2}>5. Acceptable use</h2>
        <p style={s.p}>You may not use WanderZenAI to:</p>
        <ul>
          <li style={s.li}>Generate content for resale or commercial redistribution without permission</li>
          <li style={s.li}>Attempt to circumvent usage limits or access controls</li>
          <li style={s.li}>Reverse-engineer or scrape our platform</li>
          <li style={s.li}>Use automated tools to generate itineraries at scale</li>
        </ul>

        <h2 style={s.h2}>6. Intellectual property</h2>
        <p style={s.p}>The WanderZenAI platform, brand, and technology are owned by WanderZenAI. Itineraries generated for you are yours to use personally. You grant us permission to use anonymised trip data to improve our AI models.</p>

        <h2 style={s.h2}>7. Limitation of liability</h2>
        <p style={s.p}>WanderZenAI is not liable for any travel incidents, losses, or damages arising from use of our itineraries. We are a planning tool, not a travel agency or tour operator. Always purchase appropriate travel insurance.</p>

        <h2 style={s.h2}>8. Changes to terms</h2>
        <p style={s.p}>We may update these terms. Continued use of the service after changes constitutes acceptance. We will notify users of material changes by email.</p>

        <h2 style={s.h2}>9. Contact</h2>
        <p style={s.p}><a href="mailto:travel@wanderzenai.com" style={{ color: '#00d4aa' }}>travel@wanderzenai.com</a></p>
      </div>
    </div>
  );
}
